language: php

sudo: false

php:
  - 7.1

services:
  - redis-server
  - memcached

env:
  - REDIS_SERVER_HOST=127.0.0.1 REDIS_SERVER_PORT=6379 MEMCACHED_POOL=[["127.0.0.1",11211]]

before_script:
  - composer selfupdate
  - composer update -o --no-interaction --prefer-stable
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_success:
  - vendor/bin/coveralls

matrix:
  fast_finish: true
