language: php
os: linux
dist: xenial

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

services:
  - redis
  - memcached

env:
  - REDIS_SERVER_HOST=127.0.0.1 REDIS_SERVER_PORT=6379 MEMCACHED_POOL=[["127.0.0.1",11211]]

before_script:
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - pecl install igbinary
  - pecl install msgpack

install:
  - composer update -o --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
