language: php

sudo: false

php:
  - 7.1

services:
  - redis-server
  - memcached

env:
  - REDIS_SERVER_HOST=127.0.0.1 REDIS_SERVER_PORT=6379

before_script:
  - composer selfupdate
  - composer update -o --no-interaction --prefer-stable
  - pecl install redis
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml

after_success:
  - vendor/bin/coveralls

matrix:
  fast_finish: true
