language: php

sudo: false

php:
  - 7.1

services:
  - redis-server
  - memcached

env:
  - REDIS_SERVER_HOST=localhost

before_script:
  - composer selfupdate
  - composer update -o --dev --no-interaction
  - pecl install redis
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_success:
  - vendor/bin/coveralls

matrix:
  fast_finish: true
