name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }} - Redis ${{ matrix.redis }}

    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'
        redis:
          - 5
          - 6
          - 7

    services:
      redis:
        image: redis:${{ matrix.redis }}
        options: --health-cmd="redis-cli ping" --health-retries=3 --health-interval=10s --health-timeout=5s
        ports:
          - 6379:6379
      memcached:
        image: memcached
        ports:
          - 11211:11211

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php }} with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, memcached
          ini-values: opcache.enable=0
          tools: composer:v2
          coverage: pcov

      - name: Install composer and update
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: highest
          composer-options: '-o --prefer-stable --no-progress --no-interaction'

      - name: Run unit tests
        run: vendor/bin/phpunit --verbose
